### PR TITLE
Calculate stat summary

### LINKED ISSUE #17: Write function and create tests for calculate_stat_summary()

### PR DESCRIPTION
**Pull request by Davidwang11**
Add new test cases and modify calculate_stat_summary() function

### CODE REVIEW

**Comment by cuthchow** [comment]
I'm not sure why data_type is being used as an argument for the calculate_stat_summary since that should have already been specified at the data acquisition step. The concern is that the 'data_type' specified by the user of the calculate_stat_summary function might not actually exist in the dataframe which is being passed into the function.

**Comment by Davidwang11** [comment]
Only with the dataframe itself,  I can't figure out this is a cases data or mortality data. There are different columns in these different dataframes to summarize information. I need to read the data_type information from somewhere.

**Comment by Davidwang11** [comment]
The data_type does not match the dataframe, the function will raise an error.

**Comment by jessie14** [comment]
The function doesn't need to know which data_type was used, it just needs to work with the columns that are in the given dataframe. For example, no matter what data type was used, there will be a column that starts with 'date_' and cumulative column will start with 'cumulative_ ' and you can use string matching to identify those columns

**Comment by Davidwang11** [comment]
I think it's not just df.describe() things. I need to know what I need to summarize. The people who call this function just pass the same data_type parameter as they call get_covid_data() function.

**Comment by Davidwang11** [comment]
If I have the date_type parameter passed, it's easier for me to do the summary.

**Comment by jessie14** [comment]
The easiest way would be to just specify the column to summarize as an input function.  The function right now wouldn't work if they user passes in a data_type different from the one that was actually used in get_covid_data, and it doesn't defensively program against it either

**Comment by Davidwang11** [comment]
I have checked the validity of the input parameter in the function. It will raise an error with the corresponding error message if the parameter does not match.

**Comment by jessie14** [comment]
Just one final comment, your test coverage is only 62% while the other functions are all 90% plus, would be nice to have better coverage for your function if possible, but we can update that later. I'll merge the PR and make a new issue about test coverage.

**Pull request merged**
